/**
 * Transport to the HIVE core.
 *
 * The console speaks to one of two sources and says which on screen:
 *
 *   live      the local core service, driving the analysis in real time
 *   recorded  a snapshot generated by running that same service over every
 *             replay position ahead of time
 *
 * The recorded source exists so the hosted demo works with no backend. It is
 * not a mock: every byte in it came out of the real engine. The console never
 * fabricates a finding, a plan or a verification, and it labels the recorded
 * source plainly rather than implying a live service is attached.
 */

import type {
  Architecture,
  FindingsEnvelope,
  Health,
  ImmunityPattern,
  ReplayState,
  ScenarioDescriptor,
  SwarmConfig,
  SwarmResult,
} from '../lib/types';

const API_BASE = (import.meta.env.VITE_HIVE_API_BASE ?? 'http://127.0.0.1:8000').replace(/\/$/, '');
const API = `${API_BASE}/api/v1`;
const SNAPSHOT = `${import.meta.env.BASE_URL}demo`;

export type SourceKind = 'live' | 'recorded';

export class TransportError extends Error {
  constructor(
    message: string,
    readonly hint?: string,
  ) {
    super(message);
    this.name = 'TransportError';
  }
}

export interface ApplyResult {
  plan: FindingsEnvelope['plans'][number];
  state: ReplayState;
  findings: FindingsEnvelope;
}

export interface Transport {
  readonly kind: SourceKind;
  scenarios(): Promise<ScenarioDescriptor[]>;
  architecture(scenario: string): Promise<Architecture>;
  state(scenario: string, cursor: number): Promise<ReplayState>;
  findings(scenario: string, cursor: number): Promise<FindingsEnvelope>;
  apply(scenario: string, planId: string): Promise<ApplyResult>;
  immunity(scenario: string): Promise<ImmunityPattern[]>;
  promote(scenario: string, patternId: string, to: string): Promise<ImmunityPattern>;
  simulate(config: SwarmConfig): Promise<SwarmResult>;
  /** Parameters the source can actually vary. Recorded sources hold some fixed. */
  labConstraints(): { held: (keyof SwarmConfig)[]; populations: number[] };
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

async function json<T>(url: string, init?: RequestInit): Promise<T> {
  let response: Response;
  try {
    response = await fetch(url, init);
  } catch {
    throw new TransportError(
      'Cannot reach the HIVE core service.',
      `Start it with: cd services/core && uv run uvicorn hive_core.main:app --port 8000`,
    );
  }
  if (!response.ok) {
    let detail = `${response.status} ${response.statusText}`;
    try {
      const body = (await response.json()) as { detail?: string };
      if (body.detail) detail = body.detail;
    } catch {
      /* the body was not JSON; the status line is the best description we have */
    }
    throw new TransportError(detail);
  }
  return (await response.json()) as T;
}

// ---------------------------------------------------------------------------
// Live service
// ---------------------------------------------------------------------------

function replayBase(scenario: string): string {
  return `${API}/replays/${encodeURIComponent(scenario)}`;
}

/**
 * Drive the replay to an absolute cursor position.
 *
 * The service's cursor only moves forward, so rewinding means resetting and
 * replaying. That is not a workaround: replaying from the ledger is how the
 * engine reproduces a state, and doing it on every scrub is what makes the
 * timeline honest rather than a cached picture.
 */
async function seek(scenario: string, cursor: number): Promise<void> {
  await json(`${replayBase(scenario)}/reset`, { method: 'POST' });
  if (cursor > 0) {
    await json(`${replayBase(scenario)}/advance?to_sequence=${cursor}`, { method: 'POST' });
  }
}

export const liveTransport: Transport = {
  kind: 'live',

  async scenarios() {
    const body = await json<{ scenarios: ScenarioDescriptor[] }>(`${API}/scenarios`);
    return body.scenarios;
  },

  architecture(scenario) {
    return json<Architecture>(`${replayBase(scenario)}/architecture`);
  },

  async state(scenario, cursor) {
    await seek(scenario, cursor);
    return json<ReplayState>(`${replayBase(scenario)}/state`);
  },

  findings(scenario) {
    return json<FindingsEnvelope>(`${replayBase(scenario)}/findings`);
  },

  apply(scenario, planId) {
    return json<ApplyResult>(`${replayBase(scenario)}/plans/${encodeURIComponent(planId)}/apply`, {
      method: 'POST',
    });
  },

  async immunity(scenario) {
    const body = await json<{ patterns: ImmunityPattern[] }>(`${replayBase(scenario)}/immunity`);
    return body.patterns;
  },

  async promote(scenario, patternId, to) {
    const body = await json<{ pattern: ImmunityPattern }>(
      `${replayBase(scenario)}/immunity/${encodeURIComponent(patternId)}/promote`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ to }),
      },
    );
    return body.pattern;
  },

  simulate(config) {
    return json<SwarmResult>(`${API}/lab/simulate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(config),
    });
  },

  labConstraints() {
    return { held: [], populations: [12, 24, 48, 96] };
  },
};

// ---------------------------------------------------------------------------
// Recorded snapshot
// ---------------------------------------------------------------------------

interface RecordedStep {
  cursor: number;
  state: ReplayState;
  findings: FindingsEnvelope;
}

interface RecordedScenario {
  architecture: Architecture;
  steps: RecordedStep[];
  contained: ApplyResult & { immunity: ImmunityPattern[] };
}

interface RecordedIndex {
  generated_at: string;
  engine_version: string;
  scenarios: ScenarioDescriptor[];
  lab: { held: (keyof SwarmConfig)[]; populations: number[]; keys: string[] };
}

export function labKey(config: SwarmConfig): string {
  return [
    config.population,
    config.shared_memory,
    config.external_access,
    config.perturbation,
  ].join('__');
}

/**
 * A recorded source keeps per-scenario containment state in memory for the life
 * of the page, so applying a plan changes what the console shows exactly as it
 * would against the live service.
 */
function createRecordedTransport(): Transport {
  const cache = new Map<string, Promise<RecordedScenario>>();
  const contained = new Set<string>();
  let index: Promise<RecordedIndex> | null = null;

  const loadIndex = () => (index ??= json<RecordedIndex>(`${SNAPSHOT}/index.json`));

  const loadScenario = (scenario: string) => {
    let entry = cache.get(scenario);
    if (!entry) {
      entry = json<RecordedScenario>(`${SNAPSHOT}/${scenario}.json`);
      cache.set(scenario, entry);
    }
    return entry;
  };

  const stepAt = async (scenario: string, cursor: number) => {
    const recorded = await loadScenario(scenario);
    const exact = recorded.steps.find((step) => step.cursor === cursor);
    return exact ?? recorded.steps[recorded.steps.length - 1];
  };

  return {
    kind: 'recorded',

    async scenarios() {
      return (await loadIndex()).scenarios;
    },

    async architecture(scenario) {
      return (await loadScenario(scenario)).architecture;
    },

    async state(scenario, cursor) {
      if (contained.has(scenario)) return (await loadScenario(scenario)).contained.state;
      return (await stepAt(scenario, cursor)).state;
    },

    async findings(scenario, cursor) {
      if (contained.has(scenario)) return (await loadScenario(scenario)).contained.findings;
      return (await stepAt(scenario, cursor)).findings;
    },

    async apply(scenario) {
      const recorded = await loadScenario(scenario);
      contained.add(scenario);
      return recorded.contained;
    },

    async immunity(scenario) {
      if (!contained.has(scenario)) return [];
      return (await loadScenario(scenario)).contained.immunity;
    },

    async promote(scenario, patternId, to) {
      const patterns = await this.immunity(scenario);
      const pattern = patterns.find((candidate) => candidate.id === patternId);
      if (!pattern) throw new TransportError(`No immunity pattern ${patternId}.`);
      const legal: Record<string, string[]> = {
        draft: ['shadow'],
        shadow: ['active', 'draft'],
        active: ['shadow'],
      };
      if (!legal[pattern.lifecycle]?.includes(to)) {
        throw new TransportError(
          `Cannot move ${patternId} from ${pattern.lifecycle} to ${to}.`,
          'A pattern must be observed in shadow before it is allowed to act.',
        );
      }
      pattern.lifecycle = to as ImmunityPattern['lifecycle'];
      pattern.promoted_at = new Date().toISOString();
      return pattern;
    },

    async simulate(config) {
      const meta = await loadIndex();
      const key = labKey(config);
      if (!meta.lab.keys.includes(key)) {
        throw new TransportError(
          'This combination was not recorded.',
          'Run the core service locally to explore the full parameter space.',
        );
      }
      const result = await json<SwarmResult>(`${SNAPSHOT}/lab/${key}.json`);
      return { ...result, config: { ...result.config, ...config } };
    },

    labConstraints() {
      return { held: ['connectivity', 'delegation'], populations: [12, 24, 48, 96] };
    },
  };
}

export const recordedTransport = createRecordedTransport();

// ---------------------------------------------------------------------------
// Source selection
// ---------------------------------------------------------------------------

export async function probeHealth(): Promise<Health | null> {
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 2500);
    const response = await fetch(`${API}/health`, { signal: controller.signal });
    clearTimeout(timer);
    if (!response.ok) return null;
    return (await response.json()) as Health;
  } catch {
    return null;
  }
}

/** Prefer the live service; fall back to the recording when it is not running. */
export async function selectTransport(): Promise<{ transport: Transport; health: Health | null }> {
  const health = await probeHealth();
  return { transport: health ? liveTransport : recordedTransport, health };
}

export { API_BASE };
